version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=mighty-cougar-32942.upstash.io
      - REDIS_PORT=6379  
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=G13m8sa4
      - DB_NAME=shortlinks
    env_file:
      - .env
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: G13m8sa4
      POSTGRES_DB: shortlinks
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

